name: MineTweaks
version: @version@
main: me.jishuna.minetweaks.MineTweaks
authors: [Jishuna]
api-version: 1.18

commands:
  minetweaks:
    description: 'Base plugin command'
    aliases: [mt]
permissions:
  minetweaks.command:
    default: true
  minetweaks.command.tweaks:
    default: true
  minetweaks.command.toggle:
    default: true
  minetweaks.command.status:
    default: true
  minetweaks.command.info:
    default: true
  minetweaks.command.reload:
    default: op
    
